### ISSUE TITLE
Unable to generate grammar and list of cmd line options

### ISSUE THREAD

**Issue by Sadiq1811** [clifuzzer/fse2022-clifuzzer#2]
Error logs:

root@bapvedev089:/home/sadiq/fse2022-clifuzzer# ./clifuzzer --get-options -o outputdir/perfq_app.options ./perfq_app
Test binary: ./perfq_app!
Writing to: outputdir/perfq_app.options

Traceback (most recent call last):
  File "/home/sadiq/fse2022-clifuzzer/./clifuzzer", line 134, in <module>
    for opt in opt_list:
`TypeError: 'NoneType' object is not iterable`

root@bapvedev089:/home/sadiq/fse2022-clifuzzer# ./clifuzzer --get-options -o outputdir/perfq-gram.json ./perfq_app
Test binary: ./perfq_app!
Writing to: outputdir/perfq-gram.json

Traceback (most recent call last):
  File "/home/sadiq/fse2022-clifuzzer/./clifuzzer", line 134, in <module>
    for opt in opt_list:
`_TypeError: 'NoneType' object is not iterable_`

Any thoughts about this?

**Comment by SarahMAlzahrani** [comment]
Hi 
same issue @Sadiq1811 with me also 
any suggestions to fix this error ??? @clifuzzer @vrthra 

Traceback (most recent call last):
File "/home/sadiq/fse2022-clifuzzer/./clifuzzer", line 134, in
for opt in opt_list:
TypeError: 'NoneType' object is not iterable

**Comment by vrthra** [comment]
Not sure; I will take a look at it once I have a bit more bandwidth; Please provide the details (OS version, Python version etc.).

**Comment by SarahMAlzahrani** [comment]
> Not sure; I will take a look at it once I have a bit more bandwidth; Please provide the details (OS version, Python version etc.).
--------
Hi
thanks for your response I used Python v3.8.10 on Linux 
oracle VM VirtualBox 
OS: ubuntu 20.04.5
 I hope you have time to check the issue 
thanks
Sarah
